### ISSUE TITLE
feat: 

### ISSUE THREAD

**Issue by Phil0xFF** [capawesome-team/capacitor-plugins#85] opened 2023-10-19 21:29 UTC
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Cloudinary
- [ ] Datetime Picker
- [X] File Opener
- [ ] File Picker
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Screen Orientation

### Current problem

Users are encountering inconvenience while attempting to preview large video files. The current system mandates that the entire video file be downloaded before it can be previewed, which results in a suboptimal user experience particularly for large files.

### Preferred solution

Implement a feature that allows video or other files to be streamed directly from URLs. This could help the user by minimizing the waiting time.

**Comment by robingenz** [comment] 2023-10-20 06:13
I close this as duplicate of #86

**Closed by robingenz** 2023-10-20 06:13 UTC
Labels: duplicate, needs: triage, feature
