### ISSUE TITLE
bug: Invalid column latitude

### ISSUE THREAD

**Issue by loremru** [capawesome-team/capacitor-plugins#82] opened 2023-10-12 11:08 UTC
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Opener
- [X] File Picker
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Screen Orientation

### Did you test the latest version?

- [X] I use the latest version

### Platform(s)

- [X] Android
- [ ] iOS
- [ ] Web

### Current behavior

select video
```
getModifiedAtFromUri failed.
java.lang.IllegalArgumentException: Invalid column latitude at android.database.DatabaseUtils.readExceptionFromParcel(D
```

### Expected behavior

select a video

### Reproduction

-

### Steps to reproduce

1. pickVideo
2. Android 10 + Pixel 6 API 29 Android Studio Virtual Device

### Other information

Android 14 is ok, ios too

### Capacitor doctor

💊   Capacitor Doctor  💊 

Latest Dependencies:

  @capacitor/cli: 5.5.0
  @capacitor/core: 5.5.0
  @capacitor/android: 5.5.0
  @capacitor/ios: 5.5.0

Installed Dependencies:

  @capacitor/cli: 5.4.2
  @capacitor/core: 5.4.2
  @capacitor/android: 5.4.2
  @capacitor/ios: 5.4.2

[success] iOS looking great! 👌
[success] Android looking great! 👌

### Before submitting

- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment] 2023-10-12 11:11
This is just a debugging message. You should still be able to select a video. I close this as duplicate of #79.

**Comment by loremru** [comment] 2023-10-12 11:15
@robingenz No, it isn't. Plugin returns nothing.
`Sending plugin error: {"save":false,"callbackId":"34137618","pluginId":"FilePicker","methodName":"pickMedia","success":false,"error":{"message":"Invalid column latitude"}}`

**Comment by robingenz** [comment] 2023-10-12 11:20
In this case, please provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) using [this template](https://github.com/capawesome-team/.capacitor-app) in a public GitHub repository so I can debug the issue.
Please also provide the corresponding video file.

**Comment by loremru** [comment] 2023-10-12 12:16
@robingenz 
https://github.com/loremru/capacitor-file-picker-reproduction

Android 10 + Pixel 6 API 29 Android Studio Virtual Device
video:
https://drive.google.com/file/d/1MI7uYUAjOMdX1heqPsNSpYPRefz0Yhdl/view?usp=sharing

**Comment by robingenz** [comment] 2023-10-12 14:09
I was able to reproduce the issue in the emulator.
The problem is not with this plugin but with the Google Photos app (see https://issuetracker.google.com/issues/155579897). The version installed in the emulator has a bug. When selecting a video, the latitude column is also queried which is not allowed. This bug is fixed in the current version of the Google Photos app.
For this reason i am closing this issue.

------

Related to https://github.com/HBiSoft/PickiT/issues/17#issuecomment-623418998

**Closed by robingenz** 2023-10-12 14:09 UTC
Labels: platform: android, needs: triage, bug/fix, package: file-picker
