### ISSUE TITLE
feat: Output upload progression in Javascript?

### ISSUE THREAD

**Issue by user080975** [capawesome-team/capacitor-plugins#41] opened 2023-06-23 23:20 UTC
### Current problem

Hi,

I notice when running the plugin in Xcode console there is upload progression being printed. Is it possible to output this in Javascript in Capacitor?

Thank You!

### Preferred solution

Output upload progress in Javascript.

**Comment by robingenz** [comment] 2023-06-24 04:56
Closed as duplicate of #7

**Closed** 2023-06-24 04:56 UTC
Labels: duplicate, needs: triage, feature, package: cloudinary
