### ISSUE TITLE
bug(file-picker): `pickFiles (...)` doesn't work first time on Safari

### ISSUE THREAD

**Issue by babycourageous** [capawesome-team/capacitor-plugins#14] opened 2023-02-14 16:15 UTC
**Plugin version:**
0.5.7

**Platform(s):**
Safari Web

**Current behavior:**
When first calling the command `pickFiles` on safari (ie from button click on first load of page) - nothing happens, it fails silently (no file picker shown). 
When calling the function a second time (pressing the button again), everything works as expected.

If you refresh the page, this same series of events occurs. so seems to maybe be an initialization related issue?

Everything is aok on other browsers so far!

Thanks!

**Expected behavior:**
First call to `pickFiles` should open the file picker

**Steps to reproduce:**
the quickest way to reproduce this is to run your capacitor plugin demo in safari and go to the FilePicker screen. 
Click the Pick Files button once - nothing happens
Click the Pick Files button a second time - file picker window opens

**Capacitor doctor:**

```
Latest Dependencies:

  @capacitor/cli: 4.6.3
  @capacitor/core: 4.6.3
  @capacitor/android: 4.6.3
  @capacitor/ios: 4.6.3

Installed Dependencies:

  @capacitor/cli: 4.6.1
  @capacitor/core: 4.6.1
  @capacitor/android: 4.6.1
  @capacitor/ios: 4.6.1

[success] iOS looking great! 👌
[success] Android looking great! 👌```

**Comment by jolbax** [comment] 2023-06-09 06:46
Hi guys, I am stuck with this problem as well. Is there any workaround until the final fix has been released? 
Thx in advanced for any advice

**Comment by robingenz** [comment] 2023-12-08 21:12
I set a [bounty](https://capawesome.io/contributing/bounties/) of **$50** to solve the issue. I am looking for a clean solution, not a workaround. There is no guarantee that a solution exists. It may be a bug in safari.
Let me know if anyone wants to work on this.

**Comment by stephan-fischer** [comment] 2023-12-29 17:06
For all, which want a quick solution - the same code from FilePicker works without problems directly in js code: (here Angular):

```
import { Component } from '@angular/core';
import { Capacitor } from '@capacitor/core';
import { FilePicker } from '@capawesome/capacitor-file-picker';
import { FilePickerService } from '../file-picker.service';

register();

@Component({
    selector: 'app-tab1',
    templateUrl: 'tab1.page.html'
})
export class Tab1Page  {
    constructor(private filePicker: FilePickerService) {}

    async media() {
        const native = await Capacitor.isNativePlatform();
        const result = await (native ? FilePicker : this.filePicker).pickFiles();
        const file = result.files[0];
        console.log("FILE", file);
    }
}

```

and creating a service like this:

```
import { Injectable } from '@angular/core';
import { ConvertHeicToJpegOptions, ConvertHeicToJpegResult, PickFilesOptions, PickFilesResult, PickImagesOptions, PickImagesResult, PickMediaOptions, PickMediaResult, PickVideosOptions, PickVideosResult } from '@capawesome/capacitor-file-picker';

@Injectable({
    providedIn: 'root'
})
export class FilePickerService {

    public readonly ERROR_PICK_FILE_CANCELED = 'pickFiles canceled.';

    public async convertHeicToJpeg(
        _options: ConvertHeicToJpegOptions,
    ): Promise<ConvertHeicToJpegResult> {
        throw ('Not implemented on web.');
    }

    public async pickFiles(options?: PickFilesOptions): Promise<PickFilesResult> {
        const pickedFiles = await this.openFilePicker(options);
        if (!pickedFiles) {
            throw new Error(this.ERROR_PICK_FILE_CANCELED);
        }
        const result: PickFilesResult = {
            files: [],
        };
        for (const pickedFile of pickedFiles) {
            const file: any = {
                blob: pickedFile,
                modifiedAt: pickedFile.lastModified,
                mimeType: this.getMimeTypeFromUrl(pickedFile),
                name: this.getNameFromUrl(pickedFile),
                path: undefined,
                size: this.getSizeFromUrl(pickedFile),
            };
            if (options?.readData) {
                file.data = await this.getDataFromFile(pickedFile);
            }
            result.files.push(file);
        }
        return result;
    }

    public async pickImages(
        options?: PickImagesOptions,
    ): Promise<PickImagesResult> {
        return this.pickFiles({ types: ['image/*'], ...options });
    }

    public async pickMedia(options?: PickMediaOptions): Promise<PickMediaResult> {
        return this.pickFiles({ types: ['image/*', 'video/*'], ...options });
    }

    public async pickVideos(
        options?: PickVideosOptions,
    ): Promise<PickVideosResult> {
        return this.pickFiles({ types: ['video/*'], ...options });
    }

    private async openFilePicker(
        options?: PickFilesOptions,
    ): Promise<File[] | undefined> {
        const accept = options?.types?.join(',') || '';
        const multiple = !!options?.multiple;
        return new Promise(resolve => {
            let onChangeFired = false;
            const input = document.createElement('input');
            input.type = 'file';
            input.accept = accept;
            input.multiple = multiple;
            input.addEventListener(
                'change',
                () => {
                    onChangeFired = true;
                    const files = Array.from(input.files || []);
                    resolve(files);
                },
                { once: true },
            );
            // Workaround to detect when Cancel is selected in the File Selection dialog box.
            window.addEventListener(
                'focus',
                async () => {
                    await this.wait(1000);
                    if (onChangeFired) {
                        return;
                    }
                    resolve(undefined);
                },
                { once: true },
            );
            input.click();
        });
    }

    private async getDataFromFile(file: File): Promise<string> {
        return new Promise((resolve, reject) => {
            const reader = new FileReader();
            reader.readAsDataURL(file);
            reader.onload = () => {
                const result = typeof reader.result === 'string' ? reader.result : '';
                const splittedResult = result.split('base64,');
                const base64 = splittedResult[1] || '';
                resolve(base64);
            };
            reader.onerror = error => {
                reject(error);
            };
        });
    }

    private getNameFromUrl(file: File): string {
        return file.name;
    }

    private getMimeTypeFromUrl(file: File): string {
        return file.type;
    }

    private getSizeFromUrl(file: File): number {
        return file.size;
    }

    private async wait(delayMs: number): Promise<void> {
        return new Promise(resolve => setTimeout(resolve, delayMs));
    }
}

```

I think the problem is the plugin initialisation time  and the input click handler are to late to open

**Comment by stephan-fischer** [comment] 2023-12-29 17:45
**Solution (maybe) here**

@robingenz You could easily always import web. if now the web code is executed it will work in safari because there is no import:

**index.ts:**
```
let FilePicker: FilePickerPlugin;

 import('./web').then((web) => {
    FilePicker = registerPlugin<FilePickerPlugin>('FilePicker', {
        web:  () => new web.FilePickerWeb()
    });
 })
```

Could you please tell me, if the solution works for you?

**Comment by robingenz** [comment] 2023-12-29 21:52
@stephan-fischer Interesting! This solution would be okay for me as long as it actually works and doesn't lead to errors in the WebViews.

**Closed** 2023-12-30 09:49 UTC
Labels: bug/fix, platform: web, package: file-picker, bounty, $50

**Comment by robingenz** [comment] 2023-12-30 09:51
@stephan-fischer Thank you for closing this issue. Here you will find information on how to pay out the bounty: [How do I get paid?](https://capawesome.io/contributing/bounties/claim-a-bounty/#how-do-i-get-paid)

**Comment by stephan-fischer** [comment] 2024-01-04 14:00
@robingenz  Gladly! Here is the Expense: [https://opencollective.com/capawesome/expenses/180665](https://opencollective.com/capawesome/expenses/180665). Thanks!
