### ISSUE TITLE
bug: Module is not showing complete data 

### ISSUE THREAD

**Issue by pfargowiz** [capawesome-team/capacitor-plugins#141] opened 2024-02-19 11:41 UTC
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Compressor
- [ ] File Opener
- [ ] File Picker
- [ ] Managed Configurations
- [X] NFC
- [ ] Photo Editor
- [ ] Printer
- [ ] Screen Orientation

### Version

5.0.2

### Platform(s)

- [X] Android
- [X] iOS
- [ ] Web

### Current behavior

I used capawesome-team/capacitor-nfc plugin in my application. It performed well overall, but during my comparison with other NFC applications, I noticed some discrepancies. I scanned an NFC tag using your module. Then I scanned the same NFC tag using a separate 3rd party application from the App Store. Surprisingly, the data fields and content were significantly different. 

You can check out the difference between the data provided by your module and a 3rd party Application.
So are there any module limitations or am I missing something during implementation?

### Expected behavior

The module must be able to read all data from the NFC Tags. 

### Reproduction

https://github.com/capawesome-team/capacitor-nfc-demo

### Steps to reproduce

Framework - Ionic React
I have used the same code as given in the demo.

### Other information

Data from capacitor-nfc module
![Screenshot_2](https://github.com/capawesome-team/capacitor-plugins/assets/91066158/af3d1be1-cb2a-4e04-95af-b3e4ab148ae4)

Data from a 3rd party NFC Reader Application
![3](https://github.com/capawesome-team/capacitor-plugins/assets/91066158/ec714d85-f1a5-48de-9684-a351f82ce3ce)

### Capacitor doctor

 Capacitor Doctor   

Latest Dependencies:

  @capacitor/cli: 5.7.0
  @capacitor/core: 5.7.0
  @capacitor/android: 5.7.0
  @capacitor/ios: 5.7.0

Installed Dependencies:

  @capacitor/core: 5.4.2
  @capacitor/android: 5.4.2
  @capacitor/ios: 5.4.2
  @capacitor/cli: 5.4.2

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment] 2024-02-19 12:34
First of all, the aim of our demo app is not to display all possible NFC tag information, but simply to illustrate the use of the plugin. 

> So are there any module limitations or am I missing something during implementation?

It is possible that certain information is not yet queried by the plugin. This is simply because Android/iOS offer a wide range of interfaces. If you are missing certain information, please create a feature request and we will take a look.

For example, `dsfId` can already be retrieved under Android, see [NfcTag](https://capawesome.io/plugins/nfc/#nfctag).

Since this is not a bug, I am closing this issue.

**Closed by robingenz** 2024-02-19 12:34 UTC
Labels: needs: triage, bug/fix, package: nfc

**Comment by robingenz** [comment] 2024-02-21 09:20
As i said, certain information is not yet queried by the plugin. Please create a feature request for the information you want to retrieve and we will take a look.
