### ISSUE TITLE
bug: When I try to upload a large number of photos, I get an error in the log: "Failed to allocate a 150994960 byte allocation with 25165824 free bytes and 44MB until OOM, target footprint 247164272, growth limit 268435456."

### ISSUE THREAD

**Issue by DmitryRazhkou** [capawesome-team/capacitor-plugins#156] opened 2024-03-25 10:13 UTC
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Compressor
- [ ] File Opener
- [X] File Picker
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Printer
- [ ] Screen Orientation

### Version

5.3.0

### Platform(s)

- [X] Android
- [ ] iOS
- [ ] Web

### Current behavior

When I try to upload a large number of photos, I get an error in the log: "Failed to allocate a 150994960 byte allocation with 25165824 free bytes and 44MB until OOM, target footprint 247164272, growth limit 268435456."

### Expected behavior

Need to have a possibility to catch this error in my react function: 
const fileInputHandler = useCallback(async () => {
    try {
      const result = await FilePicker.pickImages({
        multiple: true,
        readData: true
      });
      ...
      
      
Now when I do this, I can't catch the error in catch block

### Reproduction

.

### Steps to reproduce

.

### Capacitor doctor

.

### Before submitting

- [X] I have read and followed the [bug report guidelines](https://capawesome.io/contributing/bug-reports/).
- [X] I have attached links to possibly related issues and discussions.
- [X] I understand that incomplete issues (e.g. without reproduction) are closed.

**Comment by robingenz** [comment] 2024-03-25 10:21
You should not use the `readData` option for large files. You can either use the fetch API to load a blob or you can use a Capacitor plugin to upload the files directly from the native layer. You can find more information here: [The File Handling Guide for Capacitor](https://capawesome.io/blog/the-file-handling-guide-for-capacitor/)

Since this is not a bug, I am closing this issue.

**Closed by robingenz** 2024-03-25 10:21 UTC
Labels: needs: triage, bug/fix
