### ISSUE TITLE
feat: return path "file://..." instead of "content://..."

### ISSUE THREAD

**Issue by zawmoeooo** [capawesome-team/capacitor-plugins#129] opened 2024-01-23 07:44 UTC
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Compressor
- [ ] File Opener
- [X] File Picker
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Screen Orientation

### Current problem

I cannot copy using filesystem plugin because the return path is like "content://com.miui.gallery.open/raw/%2Fstorage%2Femulated%2F0%2FDCIM%2FCamera%2FVID_20240122_183905.mp4".

### Preferred solution

"file://%2Fstorage%2Femulated%2F0%2FDCIM%2FCamera%2FVID_20240122_183905.mp4"

### Before submitting

- [X] I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
- [X] I have attached links to possibly related issues and discussions.

**Comment by robingenz** [comment] 2024-01-23 07:59
I close this as duplicate of #11. Since Android 7.0, returning `file://` scheme is discouraged, see https://developer.android.com/about/versions/nougat/android-7.0-changes.html#perm.

**Closed by robingenz** 2024-01-23 07:59 UTC
Labels: needs: triage, feature

**Comment by zawmoeooo** [comment] 2024-01-23 09:48
@robingenz , Then may I know how can copy the file to data directory with content:// path?

**Comment by robingenz** [comment] 2024-01-23 09:54
Do you copy the file **immediately** after you receive the result of pickFile?

**Comment by zawmoeooo** [comment] 2024-03-01 04:57
@robingenz , Yes, I need to copy the file to app data directory to get access for uploading to the server.
