### ISSUE TITLE
feat(app-update): Android `versionName` and iOS `MARKETING_VERSION`

### ISSUE THREAD

**Issue by co-dax** [capawesome-team/capacitor-plugins#133] opened 2024-02-03 00:51 UTC
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [X] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Compressor
- [ ] File Opener
- [ ] File Picker
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Printer
- [ ] Screen Orientation

### Current problem

The plugin is only returning app internal build number and does not return the version number publicly available on Play Store and App Store (versionName in the case of Android and MARKETING_VERSION in the case of iOS).

### Preferred solution

Include Android versionName and iOS MARKETING_VERSION in the result we get when calling `await AppUpdate.getAppUpdateInfo()`. This info is alrady available in the result of `private PackageInfo getPackageInfo()` in the case of Android so we could just add it to the response. I still didn't take a look at iOS case.

### Before submitting

- [X] I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
- [X] I have attached links to possibly related issues and discussions.

**Comment by robingenz** [comment] 2024-02-03 07:35
This is a duplicate of #115.

> This info is alrady available in the result of private PackageInfo getPackageInfo() in the case of Android so we could just add it to the response.

The last time I looked at it I couldn't find any information about it. Feel free to create a PR.

**Comment by robingenz** [comment] 2024-02-05 08:22
Regarding iOS: This `MARKETING_VERSION` is already available via `currentVersion`.

**Comment by co-dax** [comment] 2024-02-05 11:09
Yeah. You are right regarding both your last comments above.
The plugin is actually providing versionCode in the case of Android and MARKETING_VERSION/CFBundleShortVersionString in the case of iOS and I would say that MARKETING_VERSION/CFBundleShortVersionString  is not guaranteed to be unique for each release (if I am not wrong?) so we will have to make sure it is unique on our own so that we don't miss an update with this plugin which could happend if we increment CURRENT_PROJECT_VERSION/CFBundleVersion (which is required for every release) but do not increment MARKETING_VERSION/CFBundleShortVersionString.

I hope I was clear. What are your thoughts on this?
Thanks.

**Closed** 2024-02-05 11:35 UTC
Labels: feature, package: app-update

**Comment by robingenz** [comment] 2024-02-05 11:39
> so we will have to make sure it is unique on our own so that we don't miss an update with this plugin which could happend if we increment CURRENT_PROJECT_VERSION/CFBundleVersion (which is required for every release) but do not increment MARKETING_VERSION/CFBundleShortVersionString.

That's correct.

Android `versionName` will now also be available with the next update.

**Comment by co-dax** [comment] 2024-02-05 11:53
Thanks.

As a side note, I am constructing MARKETING_VERSION/CFBundleShortVersionString in such a a way that the "minor" semver part is actually CURRENT_PROJECT_VERSION/CFBundleVersion thus being able to extract CURRENT_PROJECT_VERSION/CFBundleVersion from MARKETING_VERSION/CFBundleShortVersionString.

For example, in the following MARKETING_VERSION/CFBundleShortVersionString version `2.3.11` `11` is actually CURRENT_PROJECT_VERSION/CFBundleVersion so when the plugin returns MARKETING_VERSION/CFBundleShortVersionString `2.3.11` then we can extract CURRENT_PROJECT_VERSION/CFBundleVersion from it (which in this case would be `11`).
