### ISSUE TITLE
feat: Update Plugin for Capacitor 7 Compatibility and Add Logger

### ISSUE THREAD

**Issue by fabiomartino** [capawesome-team/capacitor-plugins#370] opened 2024-12-26 12:44 UTC
### Plugin(s)

- [ ] Android Foreground Service
- [ ] Android Battery Optimization
- [ ] App Review
- [X] App Shortcuts
- [ ] App Update
- [ ] Background Task
- [ ] Badge
- [ ] Bluetooth Low Energy
- [ ] Cloudinary
- [ ] Datetime Picker
- [ ] File Compressor
- [ ] File Opener
- [ ] File Picker
- [ ] Live Update
- [ ] Managed Configurations
- [ ] NFC
- [ ] Photo Editor
- [ ] Printer
- [ ] Screen Orientation
- [ ] Speech Recognition
- [ ] Speech Synthesis
- [ ] Torch
- [ ] Zip

### Current problem

The plugin is not yet fully compatible with Capacitor 7. Additionally, the iOS plugin structure uses the traditional setup, which is less maintainable and not compatible with Swift Package Manager (SPM). Debugging on iOS could also be improved with a structured logging mechanism.

### Preferred solution

1. Refactor the iOS plugin structure to support Swift Package Manager (SPM), improving maintainability and integration.
2. Update all plugin dependencies to their latest versions for better compatibility and performance.
3. Prepare the plugin for Capacitor 7 compatibility while retaining Java 17 compatibility for the time being.
4. Add a logger utility for iOS to enhance debugging and provide better error traceability.

### Alternative options

- Maintain the current iOS plugin structure, but this would limit SPM adoption and future flexibility.
- Use a different logging approach (e.g., integrate a third-party logging framework) instead of a custom logger, but this might introduce unnecessary dependencies.

### Additional context

This change aligns the plugin with Capacitor 7 standards and leverages modern tooling for iOS development. The refactoring to SPM is especially important as it allows the plugin to be more easily included in Xcode projects using the latest dependency management practices.

### Before submitting

- [X] I have read and followed the [feature request guidelines](https://capawesome.io/contributing/feature-requests/).
- [X] I have attached links to possibly related issues and discussions.

**Comment by robingenz** [comment] 2024-12-26 14:37
Thank you for creating this issue. We will add Capacitor 7 support to all plugins as soon as the first stable version is available. I will close this as duplicate of #372.

**Closed by robingenz** 2024-12-26 14:37 UTC
Labels: needs: triage, feature
