### ISSUE TITLE
feat(file-picker): save all picked files in a temporary subfolder on iOS

### ISSUE THREAD

**Issue by massimoliani** [capawesome-team/capacitor-plugins#13] opened 2023-02-25 15:40 UTC
Working on iOS the plugin has to copy with filemanager a picked media to a tmp folder. 
The tmp folder today is located on the root folder of app container.

Is it possible to locate this temporary folder inside a capacitor/filesystem folders? For example inside /Library/Caches?

Could be a great feature to locate all files inside a sub folder for the picker "picker-tmp" so we can check for lost content and cleanup if necessary.

Last one to improve final user experience to have media stored on a sub folder, name generated as today filename, the filename inside using original filename for the media.

Thank you.

**Comment by nvahalik** [comment] 2023-07-17 18:52
@robingenz Why _does_ the FilePicker copy the file exactly?

If the user has access to the photo/video, why does it need to be duplicated?

When accessing large files, this "feature" makes our app unresponsive. There is no process or indication of what is going on.

**Comment by robingenz** [comment] 2023-07-17 19:11
@nvahalik As far as I remember, we had the problem that the app only had access to the selected file via the file picker and copying the file to a temporary app folder was a way to be able to process the file with other plugins.
However, I've also been planning to remove this copying process again (or make it optional) and take a closer look at the original problem. If you have more information or ideas feel free to share them here. It's definitely on my todo list.

**Comment by robingenz** [comment] 2023-07-17 19:36
@nvahalik I would first like to find out what the problem was at that time and how to actually solve it. 
I don't know how you process the picked file but you should have a similar problem without this workaround. If you can solve it I would be very happy about a PR.
If a `createCacheCopy` property is the solution, then I have no problem with that. I just don`t want to add a property that might be deprecated in a month, because there is a better way to solve the problem.

**Comment by nvahalik** [comment] 2023-07-17 21:28
Oh, and as far as the reason why the copy is required... it is because of this:

> This method writes a copy of the file’s data to a temporary file, which the system deletes when the completion handler returns.

Source: https://developer.apple.com/documentation/foundation/nsitemprovider/2888338-loadfilerepresentation

**Comment by robingenz** [comment] 2023-07-18 10:42
@nvahalik Thank you for your research. What would be your proposed solution?

From [Apple.com](https://developer.apple.com/videos/play/wwdc2020/10652/):

> PHPicker is the modern replacement for UIImagePickerController. In addition to its privacy-focused approach, the API also provides additional features for your app like search, multi-image selection, and the ability to zoom in or out on on the photo grid. We'll show you how PHPicker can help most apps avoid asking for direct library access and how you can implement it to improve the overall experience for people interacting with your app.

So in the long run the `UIImagePickerController` will be replaced by the `PHPickerViewController`.

**Comment by nvahalik** [comment] 2023-07-18 21:59
@robingenz Given the circumstances, I don't think the code needs the `PHPickerViewController` implementation. You always want the URI and the `UIImagePickerController` _always_ gives it to you. If you want to keep the new `PHPickerViewController`, then the implementation that currently exists is probably the best.

This problem is very similar to the issues we were facing on Android: there are 2 types of results: Content Provider URIs (`content://`) and "legacy" file URIs (`file://`).

In those instances, older code needed to be updated to support both code paths. In most cases it was a minimal change. This is mainly due to the fact that both are represented by Strings.

The case of iOS is different in that we have two distinct types at play here: `NSURL`s and `NSItemProvider`. Given how the APIs work, the _best_ approach would be to just lean into the `NSItemProvider` and increase support for them at the plugin level:

1. Don't discard them: "retain" them and keep them around until the app "releases"/deletes them. Maybe return them back as a URI `item://<uuid>`.
2. Extend Capacitor to be able to return data back directly from an `item://` URI and also support something like filters. That is, you can load a _file_ from the fileystem, if Capacitor supported `item://<uuid>` directly, you could skip the file conversion altogether and just 
4. For operations which can, extend them to support hydrating the `NSItemProvider` and allowing those to be used. This would create two code paths, but you've already got them.

I'm assuming a couple of normative use-cases here: 

1. Selecting/displaying images
  1. Displaying the originals
  2. Gathering EXIF data
  3. Type conversions
  5. Resizing/optimizing originals
  6. Displaying thumbnails/variants
2. Selecting/displaying videos
  1. Loading metadata
  2. Asset conversion/transcoding
  3. Generating thumbnails/posters
  4. Playback
  5. Trimming and other operations

If you want to avoid doing the extra work of copying files, especially large ones like we tend to use, then putting off the work of transcoding is important... you'd ideally want to pass in the `NSItemProvider` information to that process and just have it use the item directly.

Ultimately, given what Capacitor provides, a custom implementation that does all of this on a per use-case basis I think ultimately makes sense. If you're really wanting that level of control, then you've got it and having a plugin do everything is likely asking too much. It is almost trivial to just copy this picker into your own project and just have it customized. The only real thing lacking would be Capacitor natively supporting NSItemProvider resources being sent back to the WebView.

**Comment by robingenz** [comment] 2023-07-20 17:04
> Given the circumstances, I don't think the code needs the PHPickerViewController implementation. You always want the URI and the UIImagePickerController always gives it to you. If you want to keep the new PHPickerViewController, then the implementation that currently exists is probably the best.

@nvahalik Unfortunately, `UIImagePickerController` lacks a few features of `PHPickerViewController` like `selectionLimit` and `preferredAssetRepresentationMode`.
For that reason, the plugin relies on `PHPickerViewController` unless we remove features again.

Thank you very much for all the feedback. There are some very interesting ideas in there that I will take a closer look at. 
If you are interested in creating a prototype for a new plugin version, feel free to create a PR and we'll take a closer look at everything there. Otherwise, I'll get back to you as soon as I've had time to take a closer look.

**Comment by nvahalik** [comment] 2023-07-20 17:34
> For that reason, the plugin relies on PHPickerViewController unless we remove features again.

I completely understand. My increasing understanding of the problem is hopefully evident from the comments.

The `PHPPickerViewController` implementation is arguably more useful from a native standpoint. What hinders the implementation here is both our _particular_ use-case and the fact that Capacitor can't natively return back this information. It is "stuck in the past" where everything must exist on the filesystem.

@robingenz Would you have any guidance on approaching this with the main Capacitor team?

**Comment by robingenz** [comment] 2023-08-11 17:49
@nvahalik Sorry for my late response. 

> Would you have any guidance on approaching this with the main Capacitor team?

Yes, but before that I need to take a closer look at the problem. The issue is still on my todo list this year.

**Comment by nvahalik** [comment] 2023-08-11 17:53
Thanks for the response.

This is still on our radar. Our final solution was that we "forked" this module internally and reverted back to the `UIImagePicker` implementation for now. This serves us best.

However, I'd love to move this discussion up the chain if possible. Will you be at Ionic conf?

**Comment by robingenz** [comment] 2023-08-11 18:06
> Will you be at Ionic conf?

Unfortunately, I can't make it this year because I'm currently writing my master's thesis. That's why I have so little time for Capawesome at the moment. :/ But next year it is definitely planned.

**Comment by CricketLaChica** [comment] 2023-12-13 04:10
> Thanks for the response.
> 
> This is still on our radar. Our final solution was that we "forked" this module internally and reverted back to the `UIImagePicker` implementation for now. This serves us best.
> 
> However, I'd love to move this discussion up the chain if possible. Will you be at Ionic conf?

Is your forked module publicly available? I'm having a hard time accessing videos over 30 seconds using this plugin as it becomes too slow.

**Comment by robingenz** [comment] 2024-04-06 12:13
I am closing this issue as not planned for the time being as there have been no further requests for this feature.

**Closed by robingenz** 2024-04-06 12:13 UTC
Labels: platform: ios, feature, package: file-picker
